spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meet_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 19970819wy

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    org:
      springframework:
        security: info
server:
  port: 80

upload:
  baseFolder: /Users/wangyu/Desktop/upload/
  documents: documents/
  images: images/
  avatars: avatar/
  default_avatar: default.png

token:
  header: Access-Token
  head:
