spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PORT_3306_TCP_ADDR}:${DB_PORT_3306_TCP_PORT}/meet?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ${DB_ENV_MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    org:
      springframework:
        security: info
server:
  port: 80

upload:
  baseFolder: ./upload/
  documents: documents/
  images: images/
  avatars: avatar/
  default_avatar: default.png

token:
  header: Access-Token
  head:
